# Implementation of Normal Equation in python

In [56]:
import numpy as np
from numpy.linalg import pinv

# np.set_printoptions(precision= 2, sign= ' ', suppress= True)

In [57]:
x = np.array([[1, 2014, 5, 1, 45],
             [1, 1416, 3, 2, 40],
             [1, 1534, 3, 2, 30],
             [1,  852, 2, 1, 36]])

In [58]:
print(x)

[[   1 2014    5    1   45]
 [   1 1416    3    2   40]
 [   1 1534    3    2   30]
 [   1  852    2    1   36]]


In [59]:
y = np.array([[460.],
              [232.],
              [315.],
              [178.]])

In [60]:
print(y)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [61]:
theta = pinv(x) @ y 

# We use @ for matrix mul and pinv function for sudo inverse . 
Because sometimes a matrix has sudo inverse and HAS NOT inverse

In [62]:
print( x @ theta)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [63]:
print(y)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [64]:
print(np.allclose(x @ theta, y)) # x @ theta == y

True


# We can use below implementation

In [68]:
theta = pinv(x.T @ x) @x.T @ y
print(x @ theta)

[[ 460.]
 [ 232.]
 [ 315.]
 [ 178.]]


In [69]:
print(np.allclose(x @ theta, y))

True


In [70]:
#X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
#y = np.dot(X, np.array([1, 2])) + 3 # y = 1 * x_0 + 2 * x_2 + 3

In [71]:
#y